;METADATA=(Diff=true, UseCommands=true)
[/Script/HottaEditMode.HottaEditModeSetting]
HottaEditUtilityObject=/HottaUtility/HottaEditMode/HottaEditUtilityObject.HottaEditUtilityObject_C
DefaultLaneBuildProfile=(Name="OnlyPedestrian ↓↑ 300",ID=48299B25483629EBC50358B07A85BE72)
DefaultLaneBuildTags=(Mask=2818572296)
DefaultIntersectionBuildTags=(Mask=2818572312)
HottaHottaUtilityEditorToolsWidget=/HottaUtility/HottaUtilityEditorTools/WBP_EditorSmallTools.WBP_EditorSmallTools
[/Script/HottaUtilityEditorTools.HottaUtilityEditorToolsLibrary.CreateWorldMinMaps.HottaUtilityEditorTools.PresetList]
Names=LastUsed
[/Script/HottaUtilityEditorTools.HottaUtilityEditorToolsLibrary.CreateWorldMinMaps.HottaUtilityEditorTools.Preset.LastUsed]
TexSizeX=1280
TexSizeY=1280
AllGridSizeX=460800
AllGridSizeY=358400
CellNumX=9
CellNumY=7
CenterPosX=-40532
CenterPosY=131446
HeighetScale=1
