;-----------------------------------------------------------------------------------------------------------------
[ViewDistanceQuality@0]
r.SkeletalMeshLODBias=0
r.ViewDistanceScale=1
wp.Runtime.HLODLoadingRangeScale=0.9
HTRoadLightSubsystem.ImmediatelyShowDisDensity_Default = 1
HTRoadLightSubsystem.ImmediatelyShowDisDensity_Group1=2
HTRoadLightSubsystem.ImmediatelyShowDisDensity_Group2=1
r.LowImpactLocalLightsShadowMaxDistance=3000
r.OutlineOverlayMaterialMaxDrawDistance=3000
[ViewDistanceQuality@1]
r.SkeletalMeshLODBias=0
r.ViewDistanceScale=1.2
wp.Runtime.HLODLoadingRangeScale=0.9
HTRoadLightSubsystem.ImmediatelyShowDisDensity_Default = 1
HTRoadLightSubsystem.ImmediatelyShowDisDensity_Group1=2
HTRoadLightSubsystem.ImmediatelyShowDisDensity_Group2=1
r.LowImpactLocalLightsShadowMaxDistance=4000
r.OutlineOverlayMaterialMaxDrawDistance=5000
[ViewDistanceQuality@2]
r.SkeletalMeshLODBias=0
r.ViewDistanceScale=1.8
wp.Runtime.HLODLoadingRangeScale=1.0
HTRoadLightSubsystem.ImmediatelyShowDisDensity_Default = 1.5
HTRoadLightSubsystem.ImmediatelyShowDisDensity_Group1=3
HTRoadLightSubsystem.ImmediatelyShowDisDensity_Group2=1.5
r.LowImpactLocalLightsShadowMaxDistance=4500
r.OutlineOverlayMaterialMaxDrawDistance=8000
[ViewDistanceQuality@3]
r.SkeletalMeshLODBias=0
r.ViewDistanceScale=2.0
wp.Runtime.HLODLoadingRangeScale=1.0
HTRoadLightSubsystem.ImmediatelyShowDisDensity_Default = 1.5
HTRoadLightSubsystem.ImmediatelyShowDisDensity_Group1=3
HTRoadLightSubsystem.ImmediatelyShowDisDensity_Group2=2
r.LowImpactLocalLightsShadowMaxDistance=5000
r.OutlineOverlayMaterialMaxDrawDistance=10000
[ViewDistanceQuality@Cine]
r.SkeletalMeshLODBias=0
r.ViewDistanceScale=2.0
wp.Runtime.HLODLoadingRangeScale=1.0
HTRoadLightSubsystem.ImmediatelyShowDisDensity_Default = 1.5
HTRoadLightSubsystem.ImmediatelyShowDisDensity_Group1=5
HTRoadLightSubsystem.ImmediatelyShowDisDensity_Group2=2
r.LowImpactLocalLightsShadowMaxDistance=5000
r.OutlineOverlayMaterialMaxDrawDistance=12000
;-----------------------------------------------------------------------------------------------------------------
[TextureQuality@0]
r.Streaming.PoolSize=2048
[TextureQuality@1]
r.Streaming.PoolSize=2672
[TextureQuality@2]
r.Streaming.PoolSize=3184
[TextureQuality@3]
r.Streaming.PoolSize=3596
[TextureQuality@Cine]
r.Streaming.PoolSize=4096
;-----------------------------------------------------------------------------------------------------------------
[PostProcessQuality@0]
r.DOF.Gather.PostfilterMethod=1
r.LensFlareQuality=0
r.BloomQuality=5
r.LightShaftQuality=0
[PostProcessQuality@1]
r.DOF.Gather.PostfilterMethod=1
r.DOF.Gather.RingCount=5
r.LensFlareQuality=0
r.BloomQuality=5
r.LightShaftQuality=0
[PostProcessQuality@2]
r.DOF.Gather.PostfilterMethod=1
r.DOF.Gather.RingCount=5
r.LensFlareQuality=0
r.BloomQuality=5
r.LightShaftQuality=1
[PostProcessQuality@3]
r.DOF.Recombine.Quality=0
r.DOF.Gather.RingCount=5
r.LensFlareQuality=2
r.BloomQuality=5
r.LightShaftQuality=1
[PostProcessQuality@Cine]
r.DOF.Recombine.Quality=0
r.DOF.Gather.RingCount=5
r.LensFlareQuality=2
r.BloomQuality=5
r.LightShaftQuality=1
r.DOF.Gather.ResolutionDivisor=2
r.RenderTargetPoolMin=500
;-----------------------------------------------------------------------------------------------------------------
[ShadowQuality@0]
r.VolumetricFog=0
r.RaymarchFog=0
r.RaymarchFog.DistanceFieldShadow=0
r.RaymarchFog.VolumetricSDFShadow=0
r.Shadow.CSM.MaxCascades=2
r.Shadow.RadiusThreshold=0.01
r.Shadow.CacheWPOPrimitives=1
r.Shadow.ForceDisableTwoSided=1
r.Shadow.FarCascadesResolutionRatio=0.5
r.Shadow.FarCascadeIndex=3
[ShadowQuality@1]
r.VolumetricFog=0
r.RaymarchFog=0
r.RaymarchFog.DistanceFieldShadow=0
r.RaymarchFog.VolumetricSDFShadow=0
r.Shadow.CSM.MaxCascades=2
r.Shadow.RadiusThreshold=0.01
r.Shadow.CacheWPOPrimitives=1
r.Shadow.ForceDisableTwoSided=1
r.Shadow.FarCascadesResolutionRatio=0.5
r.Shadow.FarCascadeIndex=3
[ShadowQuality@2]
r.VolumetricFog=0
r.VolumetricFog.GridPixelSize=32
r.RaymarchFog=1
r.RaymarchFog.SampleMinCount=30
r.RaymarchFog.LightFunctionResolutionScale=1
r.RaymarchFog.DistanceFieldShadow=0
r.RaymarchFog.VolumetricSDFShadow=0
r.RaymarchFog.VolumetricSDFShadow.Quality=0
r.RaymarchFog.DistanceFieldTraceDistance=20000
r.RaymarchFog.VolumetricSDFShadow.FramesForFullUpdate=4
r.RaymarchFog.VolumetricSDFShadow.GridPixelSize=32
r.RaymarchFog.VolumetricSDFShadow.GridSizeZ=64
r.Shadow.RadiusThreshold=0.01
r.Shadow.CacheWPOPrimitives=0
r.Shadow.ForceDisableTwoSided=1
r.Shadow.FarCascadesResolutionRatio=0.5
r.Shadow.FarCascadeIndex=3
[ShadowQuality@3]
r.VolumetricFog=1
r.VolumetricFog.GridPixelSize=32
r.RaymarchFog=1
r.RaymarchFog.SampleMinCount=60
r.RaymarchFog.LightFunctionResolutionScale=1
r.RaymarchFog.DistanceFieldShadow=0
r.RaymarchFog.VolumetricSDFShadow=1
r.RaymarchFog.VolumetricSDFShadow.OnlyTracingBounds=1
r.RaymarchFog.VolumetricSDFShadow.Quality=2
r.RaymarchFog.DistanceFieldTraceDistance=20000
r.RaymarchFog.VolumetricSDFShadow.FramesForFullUpdate=4
r.RaymarchFog.VolumetricSDFShadow.GridPixelSize=32
r.RaymarchFog.VolumetricSDFShadow.GridSizeZ=64
r.Shadow.RadiusThreshold=0.01
r.Shadow.CacheWPOPrimitives=0
r.Shadow.ForceDisableTwoSided=0
r.Shadow.FarCascadesResolutionRatio=1
r.Shadow.FarCascadeIndex=3
[ShadowQuality@Cine]
r.Shadow.MaxResolution=2048
r.Shadow.MaxCSMResolution=2048
r.VolumetricFog=1
r.VolumetricFog.GridPixelSize=16
r.RaymarchFog=1
r.RaymarchFog.SampleMinCount=60
r.RaymarchFog.LightFunctionResolutionScale=2
r.RaymarchFog.DistanceFieldShadow=1
r.RaymarchFog.VolumetricSDFShadow=1
r.RaymarchFog.VolumetricSDFShadow.OnlyTracingBounds=1
r.RaymarchFog.VolumetricSDFShadow.Quality=2
r.RaymarchFog.DistanceFieldTraceDistance=20000
r.RaymarchFog.VolumetricSDFShadow.FramesForFullUpdate=4
r.RaymarchFog.VolumetricSDFShadow.GridPixelSize=32
r.RaymarchFog.VolumetricSDFShadow.GridSizeZ=64
r.Shadow.RadiusThreshold=0.01
r.Shadow.CacheWPOPrimitives=0
r.Shadow.ForceDisableTwoSided=0
r.Shadow.FarCascadesResolutionRatio=1
r.Shadow.FarCascadeIndex=3
[AntiAliasingQuality@0]
r.FidelityFX.FSR2.Enabled=0
r.SMAA.ClipBlendBase=0
r.SMAA.ClipBlendMultiplier=1
r.SMAA.TemporalFilter=1
r.SMAA.TemporalHistoryBias=0.4
r.SMAA.PerformingColorSpace=0
r.SMAA.IntegrateVelocities=0
r.SMAA.DilateVelocity=1
r.SMAA.NeighbourhoodClamping=1
r.SMAA.Quality=0
r.SMAA.MaxSearchSteps=4
r.SMAA.MaxSearchStepsDiagonal=4
[AntiAliasingQuality@1]
r.FidelityFX.FSR2.Enabled=0
r.SMAA.ClipBlendBase=0
r.SMAA.ClipBlendMultiplier=1
r.SMAA.TemporalFilter=1
r.SMAA.TemporalHistoryBias=0.4
r.SMAA.PerformingColorSpace=1
r.SMAA.IntegrateVelocities=0
r.SMAA.DilateVelocity=1
r.SMAA.NeighbourhoodClamping=1
r.SMAA.Quality=1
r.SMAA.MaxSearchSteps=8
r.SMAA.MaxSearchStepsDiagonal=4
[AntiAliasingQuality@2]
r.FidelityFX.FSR2.Enabled=0
r.SMAA.ClipBlendBase=0
r.SMAA.ClipBlendMultiplier=1
r.SMAA.TemporalFilter=1
r.SMAA.TemporalHistoryBias=0.4
r.SMAA.PerformingColorSpace=1
r.SMAA.IntegrateVelocities=1
r.SMAA.DilateVelocity=1
r.SMAA.NeighbourhoodClamping=1
r.SMAA.Quality=2
r.SMAA.MaxSearchSteps=16
r.SMAA.MaxSearchStepsDiagonal=8
[AntiAliasingQuality@3]
r.FidelityFX.FSR2.Enabled=0
r.SMAA.ClipBlendBase=0
r.SMAA.ClipBlendMultiplier=1
r.SMAA.TemporalFilter=1
r.SMAA.TemporalHistoryBias=0.4
r.SMAA.PerformingColorSpace=1
r.SMAA.IntegrateVelocities=1
r.SMAA.DilateVelocity=1
r.SMAA.NeighbourhoodClamping=1
r.SMAA.Quality=3
r.SMAA.MaxSearchSteps=32
r.SMAA.MaxSearchStepsDiagonal=16
[AntiAliasingQuality@Cine]
r.FidelityFX.FSR2.Enabled=0
r.SMAA.ClipBlendBase=0
r.SMAA.ClipBlendMultiplier=1
r.SMAA.TemporalFilter=1
r.SMAA.TemporalHistoryBias=0.4
r.SMAA.PerformingColorSpace=1
r.SMAA.IntegrateVelocities=1
r.SMAA.DilateVelocity=1
r.SMAA.NeighbourhoodClamping=1
r.SMAA.Quality=3
r.SMAA.MaxSearchSteps=32
r.SMAA.MaxSearchStepsDiagonal=16
;-----------------------------------------------------------------------------------------------------------------
[GlobalIlluminationQuality@0]
r.DistanceFieldAO=0
r.AO.AllowLowNumConeSteps=1
r.AOQuality=0
r.AmbientOcclusion.DistanceCulling=0
r.AmbientOcclusion.Compute=1
r.Lumen.ScreenProbeGather.DownsampleFactor=32
[GlobalIlluminationQuality@1]
r.DistanceFieldAO=0
r.AO.AllowLowNumConeSteps=1
r.AOQuality=1
r.AmbientOcclusion.DistanceCulling=0
r.AmbientOcclusion.Compute=1
r.Lumen.ScreenProbeGather.DownsampleFactor=32
[GlobalIlluminationQuality@2]
r.DistanceFieldAO=0
r.AO.AllowLowNumConeSteps=1
r.AOQuality=1
r.AmbientOcclusion.DistanceCulling=0
r.AmbientOcclusion.Compute=1
r.Lumen.ScreenProbeGather.DownsampleFactor=32
[GlobalIlluminationQuality@3]
r.DistanceFieldAO=1
r.AO.AllowLowNumConeSteps=1
r.AOQuality=1
r.AmbientOcclusion.DistanceCulling=1
r.AmbientOcclusion.Compute=0
r.Lumen.ScreenProbeGather.DownsampleFactor=32
[GlobalIlluminationQuality@Cine]
r.DistanceFieldAO=1
r.AO.AllowLowNumConeSteps=0
r.AOQuality=1
r.AmbientOcclusion.DistanceCulling=1
r.AmbientOcclusion.Compute=0
r.Lumen.ScreenProbeGather.DownsampleFactor=16
;-----------------------------------------------------------------------------------------------------------------
[EffectsQuality@0]
r.DetailMode=3
r.VolumetricCloud=0
r.VolumetricCloud.SampleClampCount=128
r.VolumetricCloud.StepSizeOnZeroConservativeDensity=4
r.VolumetricCloud.ViewRaySampleMaxCount=256
r.MaterialQualityLevel=0 ; Low quality
HTAICharacter.IgnoreBornEffectDistThreshold=3000
[EffectsQuality@1]
r.DetailMode=3
r.VolumetricCloud=0
r.VolumetricCloud.SampleClampCount=128
r.VolumetricCloud.StepSizeOnZeroConservativeDensity=4
r.VolumetricCloud.ViewRaySampleMaxCount=256
r.MaterialQualityLevel=2 ; Medium quality
HTAICharacter.IgnoreBornEffectDistThreshold=4000
[EffectsQuality@2]
r.DetailMode=3
r.VolumetricCloud=1
r.VolumetricCloud.SampleClampCount=128
r.VolumetricCloud.StepSizeOnZeroConservativeDensity=4
r.VolumetricCloud.ViewRaySampleMaxCount=256
r.MaterialQualityLevel=2 ; Medium quality
HTAICharacter.IgnoreBornEffectDistThreshold=5000
[EffectsQuality@3]
r.DetailMode=3
r.VolumetricCloud=1
r.VolumetricCloud.SampleClampCount=256
r.VolumetricCloud.StepSizeOnZeroConservativeDensity=2
r.VolumetricCloud.ViewRaySampleMaxCount=256
r.MaterialQualityLevel=1 ; High quality
HTAICharacter.IgnoreBornEffectDistThreshold=5500
[EffectsQuality@Cine]
r.DetailMode=3
r.VolumetricCloud=1
r.VolumetricCloud.SampleClampCount=256
r.VolumetricCloud.StepSizeOnZeroConservativeDensity=2
r.VolumetricCloud.ViewRaySampleMaxCount=256
r.MaterialQualityLevel=1 ; High quality
HTAICharacter.IgnoreBornEffectDistThreshold=6500
;-----------------------------------------------------------------------------------------------------------------
[ReflectionQuality@0]
r.SSR.OptimizingGhosting=0
r.SSR.Quality=0
[ReflectionQuality@1]
r.SSR.OptimizingGhosting=0
r.SSR.Quality=1
[ReflectionQuality@2]
r.SSR.OptimizingGhosting=0
r.SSR.Quality=1
[ReflectionQuality@3]
r.SSR.OptimizingGhosting=0
r.SSR.Quality=2
[ReflectionQuality@Cine]
r.SSR.OptimizingGhosting=1
r.SSR.Quality=2
;-----------------------------------------------------------------------------------------------------------------
[GraphicsQuality@0]
r.NPCWalkIK=0
r.TranslucentLightingVolume=0
FieldInteraction.Enabled=0
r.MeshBlend.Enable=0
r.VHM.Enable=0
[GraphicsQuality@1]
r.NPCWalkIK=0
r.TranslucentLightingVolume=0
FieldInteraction.Enabled=0
r.MeshBlend.Enable=0
r.VHM.Enable=1
[GraphicsQuality@2]
r.NPCWalkIK=0
r.TranslucentLightingVolume=0
FieldInteraction.Enabled=1
r.MeshBlend.Enable=0
r.VHM.Enable=1
[GraphicsQuality@3]
r.NPCWalkIK=0
r.TranslucentLightingVolume=0
FieldInteraction.Enabled=1
r.MeshBlend.Enable=1
r.MeshBlend.Quality=1
r.VHM.Enable=1
[GraphicsQuality@Cine]
r.NPCWalkIK=1
r.TranslucentLightingVolume=1
FieldInteraction.Enabled=1
r.MeshBlend.Enable=1
r.MeshBlend.Quality=1
r.VHM.Enable=1
;-----------------------------------------------------------------------------------------------------------------
[NPCQuality@0]
MassParkedVehicleSpawner.MassParkedVehicleSpawnerScale=0.3
HTMassCrowdSpawner.HTMassCrowdSpawnerScale=0.4
HTMassCrowdSpawner.HTMassCrowdFixVisualCount=8
UHTMassCrowdForceLODProcessor.MaxLODHighCount=4
UHTMassCrowdForceLODProcessor.MaxLODMediumCount=8
UHTMassCrowdForceLODProcessor.MaxLODLowCount=40
HTMassVehicleSpawner.HTMassVehicleSpawnerScale=0.4
HTMassVehicleSpawner.HTMassVehicleActiveVehiclesDis=15000  
UHTMassVehicleForceLodProcessor.MaxLODHighCount=4
UHTMassVehicleForceLodProcessor.MaxLODMediumCount=4
UHTMassVehicleForceLodProcessor.MaxLODLowCount=30
HTMassTrainSpawner.TrainCountLimit=9
HTVisualNPCManager.VisualNormalNPCCount=8
HTVisualNPCManager.VisualSimpleActorCount=20
HTAISpawnCache.DefaultDensity=1
HTAISpawnCache.DriveVehicleDensity=0.5
HTFadeComponent.SkipUpdateDis=3000
HTPlayerDrivingLimit.PlayerDrivingLimitSpawnSpeed=80
HTPlayerDrivingLimit.PlayerDrivingLimitMassSpeed=80  
[NPCQuality@1]
MassParkedVehicleSpawner.MassParkedVehicleSpawnerScale=0.4
HTMassCrowdSpawner.HTMassCrowdSpawnerScale=0.45
HTMassCrowdSpawner.HTMassCrowdFixVisualCount=8
UHTMassCrowdForceLODProcessor.MaxLODHighCount=5
UHTMassCrowdForceLODProcessor.MaxLODMediumCount=10
UHTMassCrowdForceLODProcessor.MaxLODLowCount=50
HTMassVehicleSpawner.HTMassVehicleSpawnerScale=0.45
HTMassVehicleSpawner.HTMassVehicleActiveVehiclesDis=15000  
UHTMassVehicleForceLodProcessor.MaxLODHighCount=4
UHTMassVehicleForceLodProcessor.MaxLODMediumCount=5
UHTMassVehicleForceLodProcessor.MaxLODLowCount=40
HTMassTrainSpawner.TrainCountLimit=10
HTVisualNPCManager.VisualNormalNPCCount=10
HTVisualNPCManager.VisualSimpleActorCount=25
HTAISpawnCache.DefaultDensity=1
HTAISpawnCache.DriveVehicleDensity=0.5
HTFadeComponent.SkipUpdateDis=4000
HTPlayerDrivingLimit.PlayerDrivingLimitSpawnSpeed=80
HTPlayerDrivingLimit.PlayerDrivingLimitMassSpeed=250
[NPCQuality@2]
MassParkedVehicleSpawner.MassParkedVehicleSpawnerScale=0.6
HTMassCrowdSpawner.HTMassCrowdSpawnerScale=0.6
HTMassCrowdSpawner.HTMassCrowdFixVisualCount=16
UHTMassCrowdForceLODProcessor.MaxLODHighCount=5
UHTMassCrowdForceLODProcessor.MaxLODMediumCount=12
UHTMassCrowdForceLODProcessor.MaxLODLowCount=80
HTMassVehicleSpawner.HTMassVehicleSpawnerScale=0.6
HTMassVehicleSpawner.HTMassVehicleActiveVehiclesDis=15000  
UHTMassVehicleForceLodProcessor.MaxLODHighCount=4
UHTMassVehicleForceLodProcessor.MaxLODMediumCount=7
UHTMassVehicleForceLodProcessor.MaxLODLowCount=60
HTMassTrainSpawner.TrainCountLimit=10
HTVisualNPCManager.VisualNormalNPCCount=11
HTVisualNPCManager.VisualSimpleActorCount=30
HTAISpawnCache.DefaultDensity=1
HTAISpawnCache.DriveVehicleDensity=0.6
HTFadeComponent.SkipUpdateDis=6000
HTPlayerDrivingLimit.PlayerDrivingLimitSpawnSpeed=80
HTPlayerDrivingLimit.PlayerDrivingLimitMassSpeed=250 
[NPCQuality@3]
MassParkedVehicleSpawner.MassParkedVehicleSpawnerScale=0.8
HTMassCrowdSpawner.HTMassCrowdSpawnerScale=0.8
HTMassCrowdSpawner.HTMassCrowdFixVisualCount=72
UHTMassCrowdForceLODProcessor.MaxLODHighCount=5
UHTMassCrowdForceLODProcessor.MaxLODMediumCount=14
UHTMassCrowdForceLODProcessor.MaxLODLowCount=90
HTMassVehicleSpawner.HTMassVehicleSpawnerScale=0.8
HTMassVehicleSpawner.HTMassVehicleActiveVehiclesDis=20000  
UHTMassVehicleForceLodProcessor.MaxLODHighCount=5
UHTMassVehicleForceLodProcessor.MaxLODMediumCount=8
UHTMassVehicleForceLodProcessor.MaxLODLowCount=80
HTMassTrainSpawner.TrainCountLimit=10
HTVisualNPCManager.VisualNormalNPCCount=12
HTVisualNPCManager.VisualSimpleActorCount=35
HTAISpawnCache.DefaultDensity=1
HTAISpawnCache.DriveVehicleDensity=0.6
HTFadeComponent.SkipUpdateDis=7000
HTPlayerDrivingLimit.PlayerDrivingLimitSpawnSpeed=80
HTPlayerDrivingLimit.PlayerDrivingLimitMassSpeed=250  
[NPCQuality@Cine]
MassParkedVehicleSpawner.MassParkedVehicleSpawnerScale=1
HTMassCrowdSpawner.HTMassCrowdSpawnerScale=1
HTMassCrowdSpawner.HTMassCrowdFixVisualCount=72
UHTMassCrowdForceLODProcessor.MaxLODHighCount=5
UHTMassCrowdForceLODProcessor.MaxLODMediumCount=17
UHTMassCrowdForceLODProcessor.MaxLODLowCount=100
HTMassVehicleSpawner.HTMassVehicleSpawnerScale=1
HTMassVehicleSpawner.HTMassVehicleActiveVehiclesDis=20000  
UHTMassVehicleForceLodProcessor.MaxLODHighCount=5
UHTMassVehicleForceLodProcessor.MaxLODMediumCount=10
UHTMassVehicleForceLodProcessor.MaxLODLowCount=90
HTMassTrainSpawner.TrainCountLimit=10
HTVisualNPCManager.VisualNormalNPCCount=15
HTVisualNPCManager.VisualSimpleActorCount=40
HTAISpawnCache.DefaultDensity=1
HTAISpawnCache.DriveVehicleDensity=0.6
HTFadeComponent.SkipUpdateDis=8000
HTPlayerDrivingLimit.PlayerDrivingLimitSpawnSpeed=80
HTPlayerDrivingLimit.PlayerDrivingLimitMassSpeed=250  
